/**
 * Downloads the Inter + Cairo variable webfonts from Google Fonts and rewrites
 * app/fonts.css to reference the self-hosted files (public/fonts/*.woff2).
 *
 * Run once per checkout:  pnpm fonts
 * The app works without it (system font fallback) — no build-time network dep.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

const FAMILIES = [
  { css: "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap", family: "Inter" },
  { css: "https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&display=swap", family: "Cairo" },
];

const OUT_DIR = path.join(process.cwd(), "public", "fonts");
const CSS_OUT = path.join(process.cwd(), "app", "fonts.css");

const HEADER = `/* Self-hosted webfonts — GENERATED by scripts/fetch-fonts.mjs.
   If the .woff2 files are absent the app silently falls back to the system
   stack declared in globals.css — no build-time network dependency. */
`;

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  let css = HEADER;
  let fileIndex = 0;

  for (const { css: url, family } of FAMILIES) {
    const res = await fetch(url, { headers: { "user-agent": UA } });
    if (!res.ok) throw new Error(`css2 fetch failed for ${family}: ${res.status}`);
    const text = await res.text();

    // Parse each @font-face block: subset comment, unicode-range, src url
    const blocks = text.split("/*").slice(1);
    for (const block of blocks) {
      const subset = block.slice(0, block.indexOf("*/")).trim();
      const face = block.slice(block.indexOf("*/") + 2);
      const urlMatch = face.match(/url\((https:[^)]+\.woff2)\)/);
      const rangeMatch = face.match(/unicode-range:\s*([^;]+);/);
      const weightMatch = face.match(/font-weight:\s*([^;]+);/);
      if (!urlMatch) continue;

      const fontRes = await fetch(urlMatch[1], { headers: { "user-agent": UA } });
      if (!fontRes.ok) throw new Error(`font fetch failed: ${fontRes.status}`);
      const buf = Buffer.from(await fontRes.arrayBuffer());
      const filename = `${family.toLowerCase()}-${subset || fileIndex}.woff2`.replace(/[^a-z0-9.-]/gi, "-");
      await writeFile(path.join(OUT_DIR, filename), buf);
      fileIndex++;

      css += `
@font-face {
  font-family: "${family}";
  src: url("/fonts/${filename}") format("woff2");
  font-weight: ${weightMatch ? weightMatch[1].trim() : "100 900"};
  font-style: normal;
  font-display: swap;
  ${rangeMatch ? `unicode-range: ${rangeMatch[1].trim()};` : ""}
}
`;
      console.log(`✓ ${family} / ${subset} → ${filename} (${(buf.length / 1024).toFixed(0)} kB)`);
    }
  }

  await writeFile(CSS_OUT, css);
  console.log(`✓ wrote app/fonts.css (${fileIndex} font files)`);
}

main().catch((e) => {
  console.error("Font fetch failed:", e.message);
  console.error("The app will use the system font fallback. Re-run: pnpm fonts");
  process.exit(1);
});
